//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config\boards\coreECU\connectors\main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D12, // Injector 1
	Gpio::D13, // Injector 2
	Gpio::D14, // Injector 3
	Gpio::D15, // Injector 4
	Gpio::C6, // Injector 5
	Gpio::C7, // Injector 6
	Gpio::C9, // Injector 7
	Gpio::A8, // Injector 8
	Gpio::D10, // Boost controler
	Gpio::B13, // Idle valve 1
	Gpio::B12, // Tacho output
	Gpio::D8, // Low side output 1
	Gpio::B14, // Low side output 2
	Gpio::B15, // Low side output 3
	Gpio::D9, // Fan output
	Gpio::D11, // Fuel pump output
	Gpio::E7, // DBW_PWM
	Gpio::B0, // DBW_DIS
	Gpio::B1, // DBW_DIR
	Gpio::E15, // Ignition 1
	Gpio::E14, // Ignition 2
	Gpio::E13, // Ignition 3
	Gpio::E12, // Ignition 4
	Gpio::E11, // Ignition 5
	Gpio::E10, // Ignition 6
	Gpio::E9, // Ignition 7
	Gpio::E8, // Ignition 8
}
